{% set name = "pyap" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 372ea7b6364a3d2c75ffb26ebbe269ce44d71b48620d57630548bc263a6691db
  patches:
    - patches/0001-change-build-backend-to-poetry-core.patch

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - patch       # [not win]
    - m2-patch    # [win]
  host:
    - python
    - poetry-core
    - pip
  run:
    - python

test:
  files:
    - tests
  imports:
    - pyap
  commands:
    - pip check
    # tests available in master, just copied from here: https://github.com/vladimarius/pyap/blob/master/test_parser.py
    - pytest -v tests
  requires:
    - pip
    - pytest

about:
  home: https://github.com/vladimarius/pyap
  summary: Pyap is an MIT Licensed text processing library, written in Python, for detecting and parsing addresses. Currently it supports USA, Canadian and British addresses.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    Pyap is an MIT Licensed text processing library, written in Python, for detecting and parsing addresses.
    Currently it supports US 🇺🇸, Canadian 🇨🇦 and British 🇬🇧 addresses.
  dev_url: https://github.com/vladimarius/pyap
  doc_url: https://github.com/vladimarius/pyap/blob/master/README.rst

extra:
  recipe-maintainers:
    - snegireff
